df <- read.table("household_power_consumption.txt", na.strings = "?", header = TRUE, sep = ";")
df$Date <- as.Date(df$Date , format ="%d/%m/%Y")
df1 <- subset(df, df$Date == "2007-02-01"| df$Date=="2007-02-02")
df1$datetime <- paste(df1$Date, df1$Time)
df1$datetime <- strptime(df1$datetime , format = "%Y-%m-%d %H:%M:%S")
plot(df1$datetime,df1$Sub_metering_1,type="l" ,xlab = "", ylab = "Energy sub metering")
lines(df1$datetime,df1$Sub_metering_2, col = "red")
lines(df1$datetime,df1$Sub_metering_3, col = "blue")
legend("topright",legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty =1,lwd=2, cex = 0.7)
dev.copy(png, file = "plot3.png", height=480, width = 480)
dev.off()
