par(mfrow= c(2,2), mar=c(4,4,2,4)+0.1, oma=c(2,0,0,0))
df <- read.table("household_power_consumption.txt", na.strings = "?", header = TRUE, sep = ";")
df$Date <- as.Date(df$Date , format ="%d/%m/%Y")
df1 <- subset(df, df$Date == "2007-02-01"| df$Date=="2007-02-02")
df1$datetime <- paste(df1$Date, df1$Time)
df1$datetime <- strptime(df1$datetime , format = "%Y-%m-%d %H:%M:%S")
plot(df1$datetime,df1$Global_active_power, type = "l" ,xlab = "", ylab = "Global Active Power")
plot(df1$datetime, df1$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
#df <- read.table("household_power_consumption.txt", na.strings = "?", header = TRUE, sep = ";")
df$Date <- as.Date(df$Date , format ="%d/%m/%Y")
df1 <- subset(df, df$Date == "2007-02-01"| df$Date=="2007-02-02")
df1$datetime <- paste(df1$Date, df1$Time)
df1$datetime <- strptime(df1$datetime , format = "%Y-%m-%d %H:%M:%S")
plot(df1$datetime,df1$Sub_metering_1,type="l" ,xlab = "", ylab = "Energy sub metering")
lines(df1$datetime,df1$Sub_metering_2, col = "red")
lines(df1$datetime,df1$Sub_metering_3, col = "blue")
legend("topright",legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex= 0.7,col=c("black","red","blue"), lty =1,lwd=2, bty = "n")
plot(df1$datetime,df1$Global_reactive_power, type="h", xlab ="datetime", ylab = "Global_reactive_power")
dev.copy(png, file= "plot4.png", height = 480, width = 480, units="px")
dev.off()
